In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import os
os.getcwd()

'/Users/journnie/Desktop/asia/aepython/machine_learning/skyggle/hair_loss'

In [28]:
loss_train = pd.read_csv('train.csv')
loss_train

hair_loss  stay_up_late pressure_level  coffee_consumed  \
0        Many             4           High                4   
1      Medium             1            Low                1   
2      Medium             3            Low                1   
3       A lot             5           High                3   
4      Medium             2         Medium                0   
..        ...           ...            ...              ...   
315     A lot             4      Very High                6   
316    Medium             2            Low                1   
317    Medium             2            Low                1   
318       Few             2            Low                0   
319      Many             2           High                4   

     brain_working_duration stress_level swimming hair_washing dandruff  
0                         7         High       No            N      Few  
1                         0          Low      Yes            Y      NaN  
2                         1          Low      Yes            Y      NaN  
3                         7         High       No            Y      Few  
4                         1          Low       No            Y      Few  
..                      ...          ...      ...          ...      ...  
315                      13    Very High       No            Y     Many  
316                       7          Low      Yes            Y      NaN  
317                       0          Low       No            N      NaN  
318                       0          Low       No            N      NaN  
319                       7         High       No            N      Few  

[320 rows x 9 columns]

In [29]:
loss_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   hair_loss               320 non-null    object
 1   stay_up_late            320 non-null    int64 
 2   pressure_level          320 non-null    object
 3   coffee_consumed         320 non-null    int64 
 4   brain_working_duration  320 non-null    int64 
 5   stress_level            320 non-null    object
 6   swimming                320 non-null    object
 7   hair_washing            320 non-null    object
 8   dandruff                86 non-null     object
dtypes: int64(3), object(6)
memory usage: 22.6+ KB


## Data Encoding

### hair loss

In [49]:
list(loss_train['hair_loss'].unique())

[2, 1, 3, 0]

In [58]:
hair_stat = ['Few', 'Medium', 'Many', 'A lot']
hair_stat_dict = {}
for i, hair in enumerate(hair_stat):
    hair_stat_dict[hair] = i
hair_stat_dict

{'Few': 0, 'Medium': 1, 'Many': 2, 'A lot': 3}

In [59]:
# encode? 'hair_loss'
for i, hair in enumerate(loss_train['hair_loss']):
    loss_train['hair_loss'][i] = hair_stat_dict[hair]

KeyError: 2

### pressure_level

In [62]:
loss_train['pressure_level'].unique()

array([2, 0, 1, 3], dtype=object)

In [63]:
pressure_level_list = ['Low', 'Medium', 'High', 'Very High']
pressure_level_dict = {}
for i, pressure in enumerate(pressure_level_list):
    pressure_level_dict[pressure] = i
pressure_level_dict

{'Low': 0, 'Medium': 1, 'High': 2, 'Very High': 3}

In [64]:
for i, pressure in enumerate(loss_train['pressure_level']):
    loss_train['pressure_level'][i] = pressure_level_dict[pressure]

KeyError: 2

### stress_level

In [67]:
loss_train['stress_level'].unique()

array(['High', 'Low', 'Medium', 'Very High'], dtype=object)

In [68]:
stress_level_list = ['Low', 'Medium', 'High', 'Very High']
stress_level_dict = {}
for i, stress in enumerate(stress_level_list):
    stress_level_dict[stress] = i

for i, stress in enumerate(loss_train['stress_level']):
    loss_train['stress_level'][i] = stress_level_dict[stress]

### swimming

In [73]:
swimming_list = loss_train['swimming'].unique()
swimming_list

array([0, 1], dtype=object)

In [72]:
swimming_dict = {}
for i, swim in enumerate(swimming_list):
    swimming_dict[swim] = i

for i, swim in enumerate(loss_train['swimming']):
    loss_train['swimming'][i] = swimming_dict[swim]

### hair_washing

In [74]:
hair_washing_list = loss_train['hair_washing'].unique()
hair_washing_list

array(['N', 'Y'], dtype=object)

In [75]:
hair_washing_dict = {}
for i, wash in enumerate(hair_washing_list):
    hair_washing_dict[wash] = i

for i, wash in enumerate(loss_train['hair_washing']):
    loss_train['hair_washing'][i] = hair_washing_dict[wash]

### dandruff

In [77]:
dandruff_list = loss_train['dandruff'].unique()
dandruff_list = [nan, 'Few', 'Many']

array(['Few', nan, 'Many'], dtype=object)

In [78]:
dandruff_dict = {}
for i, dandruff in enumerate(dandruff_list):
    dandruff_dict[dandruff] = i

for i, dandruff in enumerate(loss_train['dandruff']):
    loss_train['dandruff'][i] = dandruff_dict[dandruff]

### object -> int

In [80]:
loss_train['hair_loss'] =  loss_train['hair_loss'].astype('int')
loss_train['pressure_level'] = loss_train['pressure_level'].astype(int)
loss_train['stress_level'] =  loss_train['stress_level'].astype('int')
loss_train['swimming'] =  loss_train['swimming'].astype('int')
loss_train['hair_washing'] =  loss_train['hair_washing'].astype('int')
loss_train['dandruff'] =  loss_train['dandruff'].astype('int')


In [81]:
loss_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   hair_loss               320 non-null    int64
 1   stay_up_late            320 non-null    int64
 2   pressure_level          320 non-null    int64
 3   coffee_consumed         320 non-null    int64
 4   brain_working_duration  320 non-null    int64
 5   stress_level            320 non-null    int64
 6   swimming                320 non-null    int64
 7   hair_washing            320 non-null    int64
 8   dandruff                320 non-null    int64
dtypes: int64(9)
memory usage: 22.6 KB


## test model

In [108]:
from sklearn.model_selection import train_test_split

X = loss_train.iloc[:,1:-1]
y = loss_train.iloc[:,0]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state = 0)

#스케일링
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler = scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

## unscaled

In [100]:
# 스케일링 전 X_train
pd.DataFrame(X_train).describe()

stay_up_late  pressure_level  coffee_consumed  brain_working_duration  \
count       256.000         256.000          256.000                 256.000   
mean          2.004           0.531            1.180                   4.031   
std           1.721           0.924            2.131                   4.432   
min           0.000           0.000            0.000                   0.000   
25%           1.000           0.000            0.000                   1.000   
50%           2.000           0.000            0.000                   2.000   
75%           3.000           1.000            1.000                   6.000   
max           8.000           3.000           10.000                  18.000   

       stress_level  swimming  hair_washing  
count       256.000   256.000       256.000  
mean          0.641     0.238         0.488  
std           1.008     0.427         0.501  
min           0.000     0.000         0.000  
25%           0.000     0.000         0.000  
50%           0.000     0.000         0.000  
75%           1.000     0.000         1.000  
max           3.000     1.000         1.000

In [109]:
from sklearn.linear_model import LogisticRegression

#1)모델 생성
reg = LogisticRegression()
#2) 모델 훈련
reg.fit(X_train,y_train)
#3) 평가 데이터에 대한 예측 수행

y_pred =reg.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score, recall_score
#오차행렬

confusion_matrix(y_test,y_pred)

array([[22,  1,  0,  0],
       [ 6, 23,  2,  2],
       [ 2,  0,  4,  1],
       [ 0,  0,  1,  0]])

In [ ]:
#정확도, 정밀도, 재현율 지표확인
## [None, 'micro', 'macro', 'weighted']
print(f"accuracy: {accuracy_score(y_test,y_pred)}")
print(f"precision: {precision_score(y_test,y_pred, average='weighted')}")
print(f"recall : {recall_score(y_test,y_pred, average='weighted')}")

accuracy: 0.765625
precision: 0.8201822916666667
recall : 0.765625


### test

In [112]:
hair_test_unscaled = pd.read_csv('test.csv')
hair_test_unscaled

stay_up_late pressure_level  coffee_consumed  brain_working_duration  \
0              0           High                0                       7   
1              3         Medium                3                      10   
2              2            Low                1                       2   
3              0            Low                0                       2   
4              1            Low                0                       2   
..           ...            ...              ...                     ...   
75             1            Low                1                       0   
76             3      Very High                6                      13   
77             2            Low                0                       2   
78             0            Low                1                       3   
79             6           High                5                      10   

   stress_level swimming hair_washing dandruff  
0          High       No            Y     Many  
1        Medium       No            N      Few  
2           Low       No            N      NaN  
3           Low       No            Y      NaN  
4           Low       No            N      NaN  
..          ...      ...          ...      ...  
75          Low       No            N      NaN  
76    Very High       No            N     Many  
77          Low       No            N      NaN  
78          Low      Yes            Y      NaN  
79         High       No            N     Many  

[80 rows x 8 columns]

In [114]:
for i, pressure in enumerate(hair_test_unscaled['pressure_level']):
    hair_test_unscaled['pressure_level'][i] = pressure_level_dict[pressure]
    
for i, stress in enumerate(hair_test_unscaled['stress_level']):
    hair_test_unscaled['stress_level'][i] = stress_level_dict[stress]
    
for i, swim in enumerate(hair_test_unscaled['swimming']):
    hair_test_unscaled['swimming'][i] = swimming_dict[swim]
    
for i, wash in enumerate(hair_test_unscaled['hair_washing']):
    hair_test_unscaled['hair_washing'][i] = hair_washing_dict[wash]
    
for i, dandruff in enumerate(hair_test_unscaled['dandruff']):
    hair_test_unscaled['dandruff'][i] = dandruff_dict[dandruff]
    
hair_test_unscaled['pressure_level'] = hair_test_unscaled['pressure_level'].astype(int)
hair_test_unscaled['stress_level'] =  hair_test_unscaled['stress_level'].astype('int')
hair_test_unscaled['swimming'] =  hair_test_unscaled['swimming'].astype('int')
hair_test_unscaled['hair_washing'] =  hair_test_unscaled['hair_washing'].astype('int')
hair_test_unscaled['dandruff'] =  hair_test_unscaled['dandruff'].astype('int')

In [115]:
hair_test_unscaled

stay_up_late  pressure_level  coffee_consumed  brain_working_duration  \
0              0               2                0                       7   
1              3               1                3                      10   
2              2               0                1                       2   
3              0               0                0                       2   
4              1               0                0                       2   
..           ...             ...              ...                     ...   
75             1               0                1                       0   
76             3               3                6                      13   
77             2               0                0                       2   
78             0               0                1                       3   
79             6               2                5                      10   

    stress_level  swimming  hair_washing  dandruff  
0              2         0             1         2  
1              1         0             0         0  
2              0         0             0         1  
3              0         0             1         1  
4              0         0             0         1  
..           ...       ...           ...       ...  
75             0         0             0         1  
76             3         0             0         2  
77             0         0             0         1  
78             0         1             1         1  
79             2         0             0         2  

[80 rows x 8 columns]

In [116]:
y_pred =reg.predict(hair_test_unscaled.iloc[:,:-1])

### submission

In [117]:
unscaled_submit = pd.read_csv('submission.csv')
unscaled_submit

No  hair_loss
0    1          0
1    2          0
2    3          0
3    4          0
4    5          0
..  ..        ...
75  76          0
76  77          0
77  78          0
78  79          0
79  80          0

[80 rows x 2 columns]

In [118]:
unscaled_submit['hair_loss'] = y_pred
unscaled_submit

No  hair_loss
0    1          0
1    2          1
2    3          1
3    4          0
4    5          0
..  ..        ...
75  76          1
76  77          2
77  78          0
78  79          1
79  80          3

[80 rows x 2 columns]

In [119]:
unscaled_submit.to_csv('unscaled_submit.csv', index=False)

## Scaled

In [101]:
# 과학적 표기법을 숫자형으로 변환 (e^(-4) 이렇게 나오는거 소수점으로 변환)
pd.options.display.float_format = '{:.3f}'.format
np.set_printoptions(precision=2,suppress=True)

# 스케일링 후 X_train_scaled(평균, 표준편차))
pd.DataFrame(X_train_scaled).describe()

0       1       2       3       4       5       6
count 256.000 256.000 256.000 256.000 256.000 256.000 256.000
mean    0.000   0.000  -0.000  -0.000   0.000  -0.000   0.000
std     1.002   1.002   1.002   1.002   1.002   1.002   1.002
min    -1.167  -0.576  -0.555  -0.911  -0.637  -0.559  -0.977
25%    -0.585  -0.576  -0.555  -0.685  -0.637  -0.559  -0.977
50%    -0.002  -0.576  -0.555  -0.459  -0.637  -0.559  -0.977
75%     0.580   0.508  -0.084   0.445   0.357  -0.559   1.024
max     3.492   2.677   4.148   3.158   2.346   1.788   1.024

In [102]:
from sklearn.linear_model import LogisticRegression

#1)모델 생성
reg = LogisticRegression()
#2) 모델 훈련
reg.fit(X_train_scaled,y_train)
#3) 평가 데이터에 대한 예측 수행

y_pred =reg.predict(X_test_scaled)

In [110]:
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score, recall_score
#오차행렬

confusion_matrix(y_test,y_pred)

array([[22,  1,  0,  0],
       [ 6, 23,  2,  2],
       [ 2,  0,  4,  1],
       [ 0,  0,  1,  0]])

In [111]:
#정확도, 정밀도, 재현율 지표확인
## [None, 'micro', 'macro', 'weighted']
print(f"accuracy: {accuracy_score(y_test,y_pred)}")
print(f"precision: {precision_score(y_test,y_pred, average='weighted')}")
print(f"recall : {recall_score(y_test,y_pred, average='weighted')}")

accuracy: 0.765625
precision: 0.8201822916666667
recall : 0.765625


### test