### 데이터 인코딩

* 레이블 인코딩(Label encoding)

In [ ]:
import sklearn
from sklearn.preprocessing import LabelEncoder

In [2]:
names = ['Kelly', 'Journnie', 'Jelly']
encoder.fit(names)
encoder.transform(names)

array([2, 1, 0])

In [6]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)

LabelEncoder()

In [7]:
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [5]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [8]:
encoder.inverse_transform(labels)  # 라벨의 원본 값 볼 수 있음

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

* 원-핫 인코딩(One-Hot encoding)

In [24]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items) 
labels = encoder.transform(items)

labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [25]:
labels_2d = labels.reshape(-1,1) # 열은 1로 내가 결정함. -1: 행은 니가 결정해
labels_2d

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [31]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels_2d)  # onehotencoder.fit - expects 2D array
oh_labels = oh_encoder.transform(labels_2d)
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [30]:
print('One - Hot Encoding Data')
print(encoder.classes_)
print(oh_labels.toarray())
print('One - Hot Encoding Demension')
print(oh_labels.shape)

One - Hot Encoding Data
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
One - Hot Encoding Demension
(8, 6)


### 피처 스케일링과 정규화

* StandardScaler

In [41]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('features means\n',
      iris_df.mean(),
      '\n\nfeatures variances\n',
      iris_df.var())

features means
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64 

features variances
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


* MinMaxScaler

In [42]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('features min values\n',
      iris_df.min(),
      '\n\nfeatures max values\n',
      iris_df.max())

features min values
 sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64 

features max values
 sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64


* Scaler를 이용하여 학습 데이터와 테스트 데이터에 fit(), transform(), fit_transform() 적용 시 유의사항. 

In [4]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1, 1)
test_array = np.arange(0,6).reshape(-1, 1)

scaler = MinMaxScaler()

scaler.fit(trian_array)
trian_scaled = scaler.transform(train_array)

print('original:', trian_array.reshape(-1))
print('scaled:', trian_scaled.reshape(-1))

original: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
